name: Azure CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npx pm2 delete all
      - run: npx pm2 start npm -- start
